openapi: 3.0.0
tags:
  - name: Tasks
info:
  title: Flowdash API
  version: '1.0'
  termsOfServive: 'https://flowdash.com'
  description: Welcome to the Flowdash API documentation.
  contact:
    name: Developer Relations
    email: developer@flowdash.com
servers:
  - url: 'https://api.flowdash.com'
    description: Production
paths:
  '/v1/workflows/{workflow_id}/tasks':
    get:
      summary: Get tasks for a workflow
      operationId: get-v1-tasks
      description: Get workflow tasks.
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Task-Object'
      tags:
        - Tasks
components:
  schemas:
    Task:
      title: Task
      type: object
      description: The representatino of a task in Flowdash
      x-examples:
        Example:
          Stage: In Progress
          Assigned To: null
          Task URL: https://app.flowdash.com/workflows/2ylSaZ/tasks/ooCwnZ
          Company ID: 42
          Company Name: Acme Corp
          Number of Employees: 10
          Contract Value: 10000.00
          Expected Close Date: 2020-01-31
          International?: false
      properties:
        Stage:
          type: string
          description: stage
          readOnly: true
        Assigned To:
          type: string
          decsription: assigned to
          readOnly: true
        Task URL:
          type: string
          description: blah
          readOnly: true
        Company ID:
          type: string
          description: blah
          readOnly: true
        Company Name:
          type: string
          description: blah
          readOnly: true
        Number of Employees:
          type: string
          description: blah
          readOnly: true
        Contract Value:
          type: string
          description: blah
          readOnly: true
        Expected Close Date:
          type: string
          description: blah
          readOnly: true
        International?:
          type: boolean
          description: blah
          readOnly: true
      readOnly: true
      x-tags:
        - Tasks
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: The access token
  responses:
    Task-List:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Task'
          examples:
            Example:
              value:
                - Stage: In Progress
                  Assigned To: null
                  Task URL: https://app.flowdash.com/workflows/2ylSaZ/tasks/ooCwnZ
                  Company ID: 42
                  Company Name: Acme Corp
                  Number of Employees: 10
                  Contract Value: 10000.00
                  Expected Close Date: 2020-01-31
                  International?:
                - Stage: Completed
                  Assigned To: null
                  Task URL: https://app.flowdash.com/workflows/2ylSaZ/tasks/ooCwnZ
                  Company ID: 49
                  Company Name: Bread Ltd
                  Number of Employees: 19
                  Contract Value: 20000.00
                  Expected Close Date: 2020-02-13
                  International?: false
security:
  - Authorization: []
